# Generated by Django 3.0.5 on 2022-06-04 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=60)),
                ('estdt', models.DateField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('disease', models.CharField(max_length=60)),
                ('pno', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Admit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit_date', models.DateField()),
                ('hsp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospice.Hospice')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospice.Patient')),
            ],
        ),
    ]
